services:
  hubble:
    image: farcasterxyz/hubble:latest
    restart: unless-stopped
    command: ["npx", "pm2-runtime", "start", "pm2.config.cjs"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:2281/v1/info"]
      start_period: 1m
    environment:
      CATCHUP_SYNC_WITH_SNAPSHOT: "${CATCHUP_SYNC_WITH_SNAPSHOT:-true}"
      NODE_OPTIONS: "--no-warnings --max-old-space-size=8192"
      HUBBLE_ARGS: >-
        start
        --ip 0.0.0.0
        --gossip-port ${GOSSIP_PORT:-2282}
        --rpc-port ${RPC_PORT:-2283}
        --eth-mainnet-rpc-url $ETH_MAINNET_RPC_URL
        --l2-rpc-url $OPTIMISM_L2_RPC_URL
        --network ${FC_NETWORK_ID:-1}
        --rpc-subscribe-per-ip-limit ${RPC_SUBSCRIBE_PER_IP_LIMIT:-4}
        -b ${BOOTSTRAP_NODE:-/dns/nemes.farcaster.xyz/tcp/2282}
        --statsd-metrics-server ${STATSD_METRICS_SERVER:-statsd:8125}
        --hub-operator-fid ${HUB_OPERATOR_FID:-0}
        --opt-out-diagnostics ${HUB_OPT_OUT_DIAGNOSTICS:-false}
        ${HUB_OPTIONS:-}
    ports:
      - '${HTTPAPI_PORT:-2281}:${HTTPAPI_PORT:-2281}'
      - '${GOSSIP_PORT:-2282}:${GOSSIP_PORT:-2282}'
      - '${RPC_PORT:-2283}:${RPC_PORT:-2283}'
    volumes:
      - ./data/hub:/home/node/app/apps/hubble/.hub
      - ./data/rocks:/home/node/app/apps/hubble/.rocks
      - ./patches/hubble/cli.js:/home/node/app/apps/hubble/build/cli.js
    logging:
      driver: local
      options:
        max-size: 10m
        max-file: 5

  statsd:
    image: graphiteapp/graphite-statsd:1.1.10-5
    restart: unless-stopped
    profiles:
      - metrics

  grafana:
    image: grafana/grafana:10.0.3
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - ./data/grafana/provisioning:/etc/grafana/provisioning
      - ./data/grafana/grafana.ini:/etc/grafana/grafana.ini
      - grafana:/var/lib/grafana
    profiles:
      - metrics

volumes:
  grafana:
  prometheus:
